version: '3'
services:
  consul:
    command: "agent -server -ui -bootstrap -client 0.0.0.0"
    image: consul:1.2.2
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=yes
    ports:
      - "8500:8500"
  registrator:
    command: "-internal -retry-attempts -1 consul://consul.:8500"
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  developer-console:
    image: caapimcollab/mobile-developer-console:1.2.00
    ports:
      - ${MDC_PORT}:443
    environment:
     - SERVICE_IGNORE=yes
     - MAS_HOSTNAME
     - MDC_HOSTNAME
     - MDC_PORT
    volumes:
      # custom entrypoint for x509 SAN creation
     - ${PWD}/files/mdc/docker-entrypoint.sh:/docker-entrypoint.sh:rw
     - ${PWD}/config/certs/mas.cert.pem:/etc/nginx/ssl/dev-console.crt
     - ${PWD}/config/certs/mas.key:/etc/nginx/ssl/dev-console.key
  mas:
    image: aricday/mas:4.2
    build:
      context: ./files/mas
      dockerfile: Dockerfile
    hostname: mas.docker.local   
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ${PWD}/config/license.xml:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
      - ${PWD}/config/mag_license.xml:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/mag_license.xml
      - ${PWD}/files/mas/bundles/andriod_service.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/03_andriod_service.bundle
      - ${PWD}/files/mas/bundles/saml_service.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/02_saml_service.bundle
      - ${PWD}/files/mas/bundles/proxy_folder.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/04_proxy_folder.bundle
      - ${PWD}/files/mas/bundles/otk_schema.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/05_otk_schema.bundle
      # these are in MAS until MSGW quickstart load is added
      - ${PWD}/files/msgw/provision/x-add-quickstart-templates.sh:/opt/docker/rc.d/after-start/z-add-quickstart-templates.sh:rw
      - ${PWD}/files/msgw/quickstart/beer_data.json:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/quickstart/beer_data.json
    environment:
      SERVICE_IGNORE: "yes"
      SSG_CLUSTER_HOST: "mas.docker.local"
      SSG_CLUSTER_PASSWORD: "7layer"
      SSG_DATABASE_USER: "gateway"
      SSG_DATABASE_PASSWORD: "7layer"
      SSG_DATABASE_JDBC_URL: "jdbc:mysql://mysql:3306/ssg?useSSL=false"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      ACCEPT_LICENSE: "true"
      SSG_SSL_KEY: "${MAS_SSL_KEY_B64}"
      SSG_SSL_KEY_PASS: "${MAS_SSL_KEY_PASS}"
      MSGW_SSL_PUBLIC_CERT_B64:
      SSG_JVM_HEAP: "6g"
      EXTRA_JAVA_ARGS: "-XX:ParallelGCThreads=4"
  mysql:
    image: mysql:5.7
    environment:
      - SERVICE_IGNORE=yes
      - MYSQL_ROOT_PASSWORD=7layer
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=10M"
    volumes:
      - mag-otk-data:/var/lib/mysql
      # - ${PWD}/files/mas/data:/var/lib/mysql
      - ${PWD}/files/mas/dbinit:/docker-entrypoint-initdb.d    
  msgw:
    image: caapim/microgateway:latest
    ports:
      - "9443:9443"
    volumes:
      - ${PWD}/files/msgw/bundles/token_exchange.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/token_exchange.bundle
      - ${PWD}/files/msgw/bundles/RouteHttp.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/RouteHttp.bundle
      - ${PWD}/files/msgw/bundles/consul.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/consul.bundle
      - ${PWD}/config/msgw_license.xml:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      - SERVICE_IGNORE=yes
      - SSG_ADMIN_USERNAME=admin
      - SSG_ADMIN_PASSWORD=password
      - SSG_SSL_KEY=${MSGW_SSL_KEY_B64}
      - SSG_SSL_KEY_PASS=${MSGW_SSL_KEY_PASS}
      - MSGW_SSL_PUBLIC_CERT_B64=${MSGW_SSL_PUBLIC_CERT_B64}
      - SSG_LICENSE
      - SSG_INTERNAL_SERVICES=restman

      - SCALER_ENABLE=false
      - SCALER_STORAGE_TYPE=db
      - SCALER_DB_TYPE=mysql
      - SCALER_DB_HOST=cadbhost
      - SCALER_DB_PORT=3306
      - SCALER_DB_NAME=qstr
      - SCALER_DB_USER=causer
      - SCALER_DB_PASSWORD=capassword

      # For MSGW Specific REST Mode
      - ACCEPT_LICENSE=true
      - QUICKSTART_REST_MODE=true
      - QUICKSTART_REPOSITORY_TYPE=consul
      - QUICKSTART_REPOSITORY_CONSUL_HOST=consul
      - QUICKSTART_REPOSITORY_CONSUL_PORT=8500
      - QUICKSTART_REPOSITORY_CONSUL_PROTOCOL=http

      - OTK_SERVER_HOST=mas
      - OTK_SERVER_SSL_PORT=${MAS_PORT}
      - OTK_CERTIFICATE=${MAS_SSL_PUBLIC_CERT_B64}
      - OTK_CERT_VERIFY_HOSTNAME=false
volumes:
  mag-otk-data: