################################################################################
##
##  Purpose: Define a miroservice for retrieving beer data from two separate
##    databases. Define a microservice for validting a JWT and exchanging tokens
##    Protect both MS with a MSGW and leverage MAS as the OAuth hub.
##
##  Email: aric.day@ca.com
##
################################################################################
version: '3'
services:
  lac_ui:
    build:
      context: ./files/lac
      dockerfile: Dockerfile
    ports:
    - "80:8080"
    environment:
      - SERVICE_IGNORE=yes
      - RDS_HOSTNAME=lac_mysql
      - RDS_PORT=3306
      - RDS_DB_NAME=lac_admin
      - RDS_USERNAME=lac_admin
      - RDS_PASSWORD=CAdemo123
      - ca_accept_license=enu
    volumes:
      - ${PWD}/files/lac/BeerData.json:/usr/local/tomcat/bin/BeerData.json
      - ${PWD}/config/lac_license.json:/usr/local/tomcat/bin/lac_license.json
      - ${PWD}/files/lac/import_data.sh:/usr/local/tomcat/bin/import_data.sh
      - ${PWD}/files/lac/StartLiveAPICreator.sh:/usr/local/tomcat/bin/StartLiveAPICreator.sh
  lac:
    build:
      context: ./files/lac
      dockerfile: Dockerfile
    # ports:
    # - "80:8080"
    environment:
      - SERVICE_NAME=lac
      - SERVICE_TAGS=ssg-proxy
      - RDS_HOSTNAME=lac_mysql
      - RDS_PORT=3306
      - RDS_DB_NAME=lac_admin
      - RDS_USERNAME=lac_admin
      - RDS_PASSWORD=CAdemo123
      - CATALINA_OPTS=--add-modules java.xml.bind $CATALINA_OPTS
      - ca_accept_license=enu
      - ESPRESSO_FORCE_DATASOURCE=true
    volumes:
      - ${PWD}/files/lac/BeerData.json:/usr/local/tomcat/bin/BeerData.json
      - ${PWD}/config/lac_license.json:/usr/local/tomcat/bin/lac_license.json
      - ${PWD}/files/lac/import_data.sh:/usr/local/tomcat/bin/import_data.sh
      - ${PWD}/files/lac/StartLiveAPICreator.sh:/usr/local/tomcat/bin/StartLiveAPICreator.sh
  lac_mysql:
    image: mysql:5.7
    environment:
      - SERVICE_IGNORE=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lac_admin
      - MYSQL_USER=lac_admin
      - MYSQL_PASSWORD=CAdemo123
    restart: always
  mysql_beers:
    image: mysql:5.7.9
    environment:
      - SERVICE_IGNORE=yes
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${PWD}/files/mysql_beers:/docker-entrypoint-initdb.d
    restart: always
