source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'MicroservicesDemo' do

pod 'MASFoundation', '~> 1.6'
pod 'MASUI', '~> 1.6'
pod 'SVProgressHUD', '~> 2.1'

end
